CREATE TABLE PAYMENT_PROCESSOR
(
    ID   		VARCHAR(255) PRIMARY KEY,
    FLAT_FEE	DOUBLE NOT NULL
);


CREATE TABLE ACQUIRER_PLUS_PRICING
(
    PAYMENT_PROCESSOR_ID	VARCHAR(255),
    VOLUME 					INTEGER NOT NULL,
    PERCENTAGE 				DOUBLE NOT NULL,
    FOREIGN KEY (PAYMENT_PROCESSOR_ID) REFERENCES PAYMENT_PROCESSOR (ID),
    PRIMARY KEY (PAYMENT_PROCESSOR_ID, VOLUME)
);


CREATE TABLE ECOMMERCE
(
    ID	VARCHAR(255) PRIMARY KEY
);


CREATE TABLE PAYMENT(
    ID              		INT AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_PROCESSOR_ID	VARCHAR(255) NOT NULL,
    ECOMMERCE_ID			VARCHAR(255) NOT NULL,
    AMOUNT					DOUBLE NOT NULL,
    PAYMENT_DATE			DATE NOT NULL,    
    FOREIGN KEY (PAYMENT_PROCESSOR_ID) REFERENCES PAYMENT_PROCESSOR (ID),
    FOREIGN KEY (ECOMMERCE_ID) REFERENCES ECOMMERCE (ID)    
);